spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqrs
    username: swcamp
    password: swcamp
  output:
    ansi:
      enabled: always

image:
  image-dir: C:/upload/productimgs
  image-url: http://localhost:8080/productimgs/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.cqrs.products.query.dto